### ISSUE TITLE
cli: error when package lacks a license

### ISSUE THREAD

**Issue by philips** [coreos/license-bill-of-materials#1]
If a package lacks a license throw an error. Let the user override the license with a flag like:

```
license-bill-of-materials --override "github.com/coreos/etcd,BSD 3-clause"
```

**Comment by xiang90** [comment]
@philips I fixed the first part. Now we report the missing license as an error. For the second part, I feel adding a flag might be inconvenient. If we have a project that miss 5 licenses on its deps, the string list will be pretty long. Are you open to change that to an input file?

```
license-bill-of-materials --override-file file-example
```

file example

```
github.com/coreos/etcd BSD 3-clause
github.com/coreos/example Apache 2
```

**Comment by philips** [comment]
A file is fine.

**Comment by xiang90** [comment]
@philips Fixed in master.
