### ISSUE TITLE
Any plans to include other languages?

### ISSUE THREAD

**Issue by rothgar** [coreos/license-bill-of-materials#3]
I know go is the focus but is this flexible enough to make it work with other languages?

e.g.
requirements.txt
package.json

This could be invaluable to dev and legal teams in auditing project dependancies

**Comment by philips** [comment]
These are the other projects we found while researching.

Go:
- https://github.com/c4milo/licentia
- https://github.com/pmezard/licenses
- https://github.com/client9/gosupplychain

Others:
https://github.com/pivotal/LicenseFinder

**Comment by philips** [comment]
We just need a simple tool for our Go projects at CoreOS. LicenseFinder looks super complete and we might use it for our couple of python projects.

**Comment by rothgar** [comment]
Perfect, thanks for the links.
